/**
 * HOME PAGE
 */
export const homePageActionTypes = {
  REQUEST_HOME_DATA: "REQUEST_HOME_DATA",
  SET_MY_RECENT_TRACKS: "SET_MY_RECENT_TRACKS",
  SET_MY_SAVED_TRACKS: "SET_MY_SAVED_TRACKS",
  SET_MY_TOP_TRACKS: "SET_MY_TOP_TRACKS",
};
