/**
 * FEATURED PAGE
 */
export const featuredPageActionTypes = {
  FETCH_FEATURED_PAGE_DATA_START: "FETCH_FEATURED_PAGE_DATA_START",
  FETCH_FEATURED_PAGE_DATA_SUCCESS: "FETCH_FEATURED_PAGE_DATA_SUCCESS",
  FETCH_FEATURED_PAGE_DATA_ERROR: "FETCH_FEATURED_PAGE_DATA_ERROR",
  SET_MY_PLAYLISTS_FEATURED: "SET_MY_PLAYLISTS_FEATURED",
  SET_MY_RECOMMENDED_TRACKS: "SET_MY_RECOMMENDED_TRACKS",
};
