/**
 * AUTH
 */
export const authActionTypes = {
  AUTH_START: "AUTH_START",
  SPOTIFY_AUTH_START: "SPOTIFY_AUTH_START",
  SET_USER: "SET_USER",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_ERROR: "AUTH_ERROR",
};
