/**
 * HEADER
 */
export const headerActionTypes = {
  SET_HEADER_SCROLLED: "SET_HEADER_SCROLLED",
  SET_ITEM_TOOLBAR_DISPLAY: "SET_ITEM_TOOLBAR_DISPLAY",
  SET_SEARCH_BAR_DISPLAY: "SET_SEARCH_BAR_DISPLAY",
};
