export const SET_USER = "SET_USER";
export const SET_TOKEN = "SET_TOKEN";
export const SET_PLAYLISTS = "SET_PLAYLISTS";
export const SET_DISCOVER_WEEKLY = "SET_DISCOVER_WEEKLY";
export const {
  REACT_APP_CLIENT_ID,
  REACT_APP_AUTHORIZE_URL,
  REACT_APP_REDIRECT_BASE_URL,
  REACT_APP_REDIRECT_PATH,
  REACT_APP_AVATAR_MENU_PROFILE,
  REACT_APP_AVATAR_MENU_ACCOUNT,
  REACT_APP_AVATAR_MENU_LOGOUT,
  REACT_APP_HTML_HEAD_TITLE,
} = process.env;
