export const actionTypes = {
  SET_USER: "SET_USER",
  SET_TOKEN: "SET_TOKEN",
  SET_TOKEN_EXPIRY: "SET_TOKEN_EXPIRY",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_HEADER_SCROLLED: "SET_HEADER_SCROLLED",
  SET_SEARCH_BAR_DISPLAY: "SET_SEARCH_BAR_DISPLAY",
  SET_IS_PLAYLIST_PAGE: "SET_IS_PLAYLIST_PAGE",
  SET_PLAYLIST_TOOLBAR_DISPLAY: "SET_PLAYLIST_TOOLBAR_DISPLAY",
  SET_SEARCH_FILTER: "SET_SEARCH_FILTER",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
  SET_CURRENT_PLAYBACK_STATE: "SET_CURRENT_PLAYBACK_STATE",
};
