/**
 * FOOTER - SpotifyAudioPlayer
 */
export const footerActionTypes = {
  FETCH_CURRENT_PLAYBACK_STATE: "FETCH_CURRENT_PLAYBACK_STATE",
  SET_CURRENT_PLAYBACK_STATE: "SET_CURRENT_PLAYBACK_STATE",
};
