export const itemPageActionTypes = {
  /**
   * ITEM PAGE
   */
  FETCH_ITEM_PAGE_DATA_START: "FETCH_ITEM_PAGE_DATA_START",
  FETCH_ITEM_PAGE_DATA_SUCCESS: "FETCH_ITEM_PAGE_DATA_SUCCESS",
  FETCH_ITEM_PAGE_DATA_ERROR: "FETCH_ITEM_PAGE_DATA_ERROR",
  SET_IS_ITEM_PAGE: "SET_IS_ITEM_PAGE",
  SET_ITEM: "SET_ITEM",
  // -> variant "playlist"
  SET_PLAYLIST_IS_FOLLOWER: "SET_PLAYLIST_IS_FOLLOWER",
};
