/**
 * FOOTER - SpotifyAudioPlayer
 */
export const footerActionTypes = {
  FETCH_CURRENT_PLAYBACK_STATE_START: "FETCH_CURRENT_PLAYBACK_STATE_START",
  SET_CURRENT_PLAYBACK_STATE: "SET_CURRENT_PLAYBACK_STATE",
  REMOTE_CONTROL_API_ERROR: "REMOTE_CONTROL_API_ERROR",
  CLEAN_REMOTE_CONTROL_API_ERROR: "CLEAN_REMOTE_CONTROL_API_ERROR",
};
