/**
 * HOME PAGE
 */
export const homePageActionTypes = {
  FETCH_HOME_PAGE_DATA_START: "FETCH_HOME_PAGE_DATA_START",
  FETCH_HOME_PAGE_DATA_SUCCESS: "FETCH_HOME_PAGE_DATA_SUCCESS",
  FETCH_HOME_PAGE_DATA_ERROR: "FETCH_HOME_PAGE_DATA_ERROR",
};
